### ISSUE TITLE
Represent on Manage Posts view

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/publishing-checklist#4]
It would be nice to have some indicator of Publishing Checklist progress in the Manage Posts view.

**Comment by taterread** [comment]
My assumption is that checklist is non-linear, i.e. there are not steps in order, but really just an overall measurement of completeness, correct? So what is the sort of indicator? originally I wanted to have the progress bar switch from red to yellow to green to visually signify when a post was "complete" vs "half-done" such an indicator of color would be probably easier to scan (and filter by) in this view.

Here's your screengrab with a few quick ideas. Let me know specifically what the editorial folks would find useful:

![image](https://cloud.githubusercontent.com/assets/10078252/8071923/d0cd0d82-0edc-11e5-80cd-62f46fb66f7f.png)

**Comment by danielbachhuber** [comment]
> My assumption is that checklist is non-linear, i.e. there are not steps in order, but really just an overall measurement of completeness, correct?

Correct.

> So what is the sort of indicator?

Given the amount of data on the table, I'd think the priority would be small-ish and easily scannable. The progress bars best visually represent progress, but they also take up the most space.

Any other ideas?

**Comment by taterread** [comment]
Well, the 3 ideas I provided are variants of the visual language we have established in the checklist: color, progress bar, and actual count (4 of 6). 

- The progress bar takes up the most space, but most closely represents the checklist,
- The color indicator is easily scannable ( and is easily sortable, like just show me 'red' articles). However, it introduces a status (red, yellow, green) which is not technically part of the original checklist.
- Number completed: spells out the number of tasks completed, not as scannable but corresponds directly to the indicator on the publishing checklist.

My assumption is that the main use case is an Editor scanning to see which stories are properly filled out and tagged. Any "red" or "yellow" stories can be flagged and sent back to the author for further review. Here actual progress might not be the best way to go since it makes the user interpret the size of progress bar what action to take versus a simple color indicator (red, yellow, green) or even a binary indicator (complete/incomplete).

Status might make the most sense in this view, so the single color indicator might be the easiest to scan, then if the editor/author wants further details they can investigate. Also, it gives the editorial team the ability to flag fields that are higher value. I.e. article can't be published without filling this in.

Do we have any specific criteria of what information the Editor / Author might need to know from this view? Maybe let that drive the design decision vs just tossing spaghetti on the wall, no?

**Comment by danielbachhuber** [comment]
> The color indicator is easily scannable

Not for color-blind though, who we should accommodate.

> Do we have any specific criteria of what information the Editor / Author might need to know from this view? Maybe let that drive the design decision vs just tossing spaghetti on the wall, no?

@joycectang Opinions on ^^

**Comment by joycectang** [comment]
I vote for the progress bar.

Criteria for authors and editors should be the same. Use case is: authors write a post and should aim to meet all requirements of the publishing checklist so that editors mostly have to edit the copy and optimize everything on the checklist. We don't want to build in any hard stops to publishing, or have it be a trigger to return to the author. Everyone should be trained to aim for a 100% progress bar, but there will always be exceptions, like breaking news where speed is the most important factor.

**Comment by danielbachhuber** [comment]
Progress bar it is. I think I can chuck the full completed / not completed list into a hover experience too, so its easier to see what's remaining.

**Comment by taterread** [comment]
Yeah, if you can do that on click/hover and it displays the checklist, that
would be great.

On Wed, Jun 10, 2015 at 6:24 PM, Daniel Bachhuber <notifications@github.com>
wrote:

> Progress bar it is. I think I can chuck the full completed / not completed
> list into a hover experience too, so its easier to see what's remaining.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fusioneng/publishing-checklist/issues/4#issuecomment-110935367>
> .
>



-- 
 *tater read*
Senior UX Designer
tater.read@fusion.net
*m. *(646) 479-1424

 <http://fusion.net> <http://fusion.net>



 <http://fusion.net>

**Comment by danielbachhuber** [comment]
@davisshaver JavaScript still needs to be rebound for Quick Edit reload.

**Comment by danielbachhuber** [comment]
:ship:
